import { Inter } from "next/font/google";
import "./globals.css";
import { SearchContextProvider } from "./components/SearchProvider";
import { CartProvider } from "./components/CartProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ShopyShop",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <SearchContextProvider>
              {children}
          </SearchContextProvider>
        </CartProvider>
      </body>
    </html>
  );
}
